"""initial migration

Revision ID: 26371aa68595
Revises: c555b5442446
Create Date: 2026-05-10 00:18:27.429894

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '26371aa68595'
down_revision = 'c555b5442446'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_results')
    op.drop_table('users')
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('education_level', sa.String(length=50), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    with op.batch_alter_table('chat_history', schema=None) as batch_op:
        batch_op.drop_constraint('chat_history_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_constraint('notification_recipient_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['recipient_id'], ['id'])

    with op.batch_alter_table('test_result', schema=None) as batch_op:
        batch_op.drop_constraint('test_result_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.drop_constraint('uq_user_eds_iin', type_='unique')
        batch_op.drop_constraint('uq_user_eds_serial_number', type_='unique')
        batch_op.create_index(batch_op.f('ix_user_eds_iin'), ['eds_iin'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_eds_serial_number'), ['eds_serial_number'], unique=True)
        batch_op.drop_column('is_admin')
        batch_op.drop_column('is_staff')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_staff', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('is_admin', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_index(batch_op.f('ix_user_eds_serial_number'))
        batch_op.drop_index(batch_op.f('ix_user_eds_iin'))
        batch_op.create_unique_constraint('uq_user_eds_serial_number', ['eds_serial_number'])
        batch_op.create_unique_constraint('uq_user_eds_iin', ['eds_iin'])
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)

    with op.batch_alter_table('test_result', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('test_result_user_id_fkey', 'user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('notification_recipient_id_fkey', 'user', ['recipient_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('chat_history', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('chat_history_user_id_fkey', 'user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('education_level')
        batch_op.drop_column('user_id')

    op.create_table('users',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('users_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('ent_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('subjects', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('language', sa.VARCHAR(length=10), server_default=sa.text("'ru'::character varying"), autoincrement=False, nullable=True),
    sa.Column('role', sa.VARCHAR(length=20), server_default=sa.text("'user'::character varying"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    sa.UniqueConstraint('email', name='users_email_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('test_results',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('answers', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('score_vector', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('recommended_programs', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='test_results_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='test_results_pkey')
    )
    # ### end Alembic commands ###
