"""add status and staff_note to applications

Revision ID: bf64d88c6788
Revises: 26371aa68595
Create Date: 2026-05-11 01:50:55.050853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf64d88c6788'
down_revision = '26371aa68595'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=30), 
                                      nullable=False, server_default='received'))
        batch_op.add_column(sa.Column('staff_note', sa.Text(), nullable=True))

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.drop_column('staff_note')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
